kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres2-pvc
  labels:
   app: postgres
spec:
  storageClassName: mystorage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi