# Generated by Django 4.1.7 on 2023-02-20 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=models.DurationField(choices=[(datetime.timedelta(0), 'never'), (datetime.timedelta(days=1), 'day'), (datetime.timedelta(days=7), 'week'), (datetime.timedelta(days=14), 'two weeks')], default=datetime.timedelta(0)),
        ),
    ]
