# Generated by Django 4.1.7 on 2023-03-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='participant_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='timetable_app.commongroup'),
        ),
    ]
