# Generated by Django 4.1.7 on 2023-03-04 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable_app', '0002_alter_event_repeat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='master',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='participant_groups',
            field=models.ManyToManyField(blank=True, related_name='events', to='timetable_app.commongroup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.TextField(blank=True),
        ),
    ]
